[package]
name = "particle_system"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9.0"
glam = "0.30.8"
rand = "0.9.2" 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"